/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Count: typeof import('../components/NumCounter.vue')['default']
    Counter: typeof import('../components/NumCounter.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElC: typeof import('element-plus/es')['ElC']
    ElCo: typeof import('element-plus/es')['ElCo']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IEpAvatar: typeof import('~icons/ep/avatar')['default']
    IEpDocument: typeof import('~icons/ep/document')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpEditPen: typeof import('~icons/ep/edit-pen')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpGrid: typeof import('~icons/ep/grid')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpStarFilled: typeof import('~icons/ep/star-filled')['default']
    MessageTrigger: typeof import('./../components/MessageTrigger.vue')['default']
    NumCounter: typeof import('./../components/NumCounter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./../components/SubMenu.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon.vue')['default']
    UserInfo: typeof import('./../components/UserInfo.vue')['default']
  }
}
